# ── Aplicação ──────────────────────────────────────────────────────────────────
spring.application.name=markFilmes

# ── Banco de dados PostgreSQL ──────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/markfilmes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ────────────────────────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ── OMDB API ───────────────────────────────────────────────────────────────────
omdb.api.url=https://www.omdbapi.com/?t=
omdb.api.key=6585022c

# ── Servidor ───────────────────────────────────────────────────────────────────
server.port=8080

# ── Swagger / OpenAPI ──────────────────────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
